name: Frontend Docker Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Preuzmi kod
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login na Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image
      - name: Build Docker image
        run: docker build -t jovanajovicmetropolitan/cardatabase-frontend:latest .

      # 4. Push na Docker Hub
      - name: Push Docker image
        run: docker push jovanajovicmetropolitan/cardatabase-frontend:latest